version: "3.3"
services:
  database:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=abcD1234
  server:
    image: crypto-stash-stats:latest
    network_mode: host
    depends_on:
      - database
    # ports:
    #   - 5000:80
    environment:
      - SEED=true
      - ASPNETCORE_ENVIRONMENT=Development
      - CUSTOMCONNSTR_StatsDb=Server=192.168.122.93;port=5433;user id=postgres;database=postgres;pooling=true;
      - StatsDb=abcD1234
      - IdentityServerAddress=https://dev.kfntech.com