apiVersion: v1
kind: Namespace
metadata:
  name: crypto-stash

---

apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: crypto-stash
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: database

---

apiVersion: v1
kind: Service
metadata:
  name: database-external
  namespace: crypto-stash
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30020
  selector:
    app: database

---

apiVersion: v1
kind: Service
metadata:
  name: stats-server
  namespace: crypto-stash
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30021
  selector:
    app: stats-server

---

apiVersion: v1
kind: Secret
metadata:
  name: db-root
  namespace: crypto-stash
type: kubernetes.io/basic-auth
stringData:
  password: t0p-Secret

---

apiVersion: v1
kind: Secret
metadata:
  name: crypto-staging-db
  namespace: crypto-stash
type: kubernetes.io/basic-auth
stringData:
  password: Server=125.91.172.1;port=30020;user id=statsuser;password=t0p-Secret;database=crypto_staging_db;pooling=true;Timeout=30

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: crypto-stash
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: crypto-stash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgresql
          image: postgres:alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-root
                  key: password
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-server
  namespace: crypto-stash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-server
  template:
    metadata:
      labels:
        app: stats-server
    spec:
      imagePullSecrets:
        - name: registry.cn-shenzhen.aliyuncs.com
      containers:
        - name: stats-server
          image: registry.cn-shenzhen.aliyuncs.com/destinesiastudio/crypto-stash-stats:1.0.3
          env:
            - name: PGSQLCONNSTR_CryptoDb
              valueFrom:
                secretKeyRef:
                  name: crypto-staging-db
                  key: password