// <auto-generated />
using System;
using CryptoStashStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CryptoStashStats.Migrations
{
    [DbContext(typeof(FinanceContext))]
    partial class FinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("financeSchema")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BlockchainToken", b =>
                {
                    b.Property<int>("BlockchainsId")
                        .HasColumnType("integer");

                    b.Property<int>("TokensId")
                        .HasColumnType("integer");

                    b.HasKey("BlockchainsId", "TokensId");

                    b.HasIndex("TokensId");

                    b.ToTable("BlockchainToken");
                });

            modelBuilder.Entity("CryptoStashStats.Models.Blockchain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NativeTokenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NativeTokenId")
                        .IsUnique();

                    b.ToTable("Blockchains");
                });

            modelBuilder.Entity("CryptoStashStats.Models.CurrencyExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CurrencyExchanges");
                });

            modelBuilder.Entity("CryptoStashStats.Models.ExchangeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrencyExchangeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyExchangeId");

                    b.ToTable("ExchangeAccounts");
                });

            modelBuilder.Entity("CryptoStashStats.Models.ExchangeAccountApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExchangeAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeAccountId")
                        .IsUnique();

                    b.HasIndex("PublicKey", "PrivateKey")
                        .IsUnique();

                    b.ToTable("ExchangeAccountApiKeys");
                });

            modelBuilder.Entity("CryptoStashStats.Models.ExchangeAccountBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ExchangeAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Savings")
                        .HasColumnType("double precision");

                    b.Property<int>("TokenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeAccountId");

                    b.HasIndex("TokenId");

                    b.ToTable("ExchangeAccountBalances");
                });

            modelBuilder.Entity("CryptoStashStats.Models.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BuyerTokenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CurrencyExchangeId")
                        .HasColumnType("integer");

                    b.Property<double>("Current")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SellerTokenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuyerTokenId");

                    b.HasIndex("CurrencyExchangeId");

                    b.HasIndex("SellerTokenId");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("CryptoStashStats.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Ticker", "Address")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("CryptoStashStats.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BlockchainId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainId");

                    b.HasIndex("Address", "BlockchainId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptoStashStats.Models.WalletBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Savings")
                        .HasColumnType("double precision");

                    b.Property<int>("TokenId")
                        .HasColumnType("integer");

                    b.Property<int?>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletBalances");
                });

            modelBuilder.Entity("ExchangeAccountToken", b =>
                {
                    b.Property<int>("ExchangeAccountsId")
                        .HasColumnType("integer");

                    b.Property<int>("TokensId")
                        .HasColumnType("integer");

                    b.HasKey("ExchangeAccountsId", "TokensId");

                    b.HasIndex("TokensId");

                    b.ToTable("ExchangeAccountToken");
                });

            modelBuilder.Entity("TokenWallet", b =>
                {
                    b.Property<int>("TokensId")
                        .HasColumnType("integer");

                    b.Property<int>("WalletsId")
                        .HasColumnType("integer");

                    b.HasKey("TokensId", "WalletsId");

                    b.HasIndex("WalletsId");

                    b.ToTable("TokenWallet");
                });

            modelBuilder.Entity("BlockchainToken", b =>
                {
                    b.HasOne("CryptoStashStats.Models.Blockchain", null)
                        .WithMany()
                        .HasForeignKey("BlockchainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoStashStats.Models.Token", null)
                        .WithMany()
                        .HasForeignKey("TokensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoStashStats.Models.Blockchain", b =>
                {
                    b.HasOne("CryptoStashStats.Models.Token", "NativeToken")
                        .WithOne("NativeBlockchain")
                        .HasForeignKey("CryptoStashStats.Models.Blockchain", "NativeTokenId");

                    b.Navigation("NativeToken");
                });

            modelBuilder.Entity("CryptoStashStats.Models.ExchangeAccount", b =>
                {
                    b.HasOne("CryptoStashStats.Models.CurrencyExchange", "CurrencyExchange")
                        .WithMany()
                        .HasForeignKey("CurrencyExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyExchange");
                });

            modelBuilder.Entity("CryptoStashStats.Models.ExchangeAccountApiKey", b =>
                {
                    b.HasOne("CryptoStashStats.Models.ExchangeAccount", "ExchangeAccount")
                        .WithOne("ExchangeAccountApiKey")
                        .HasForeignKey("CryptoStashStats.Models.ExchangeAccountApiKey", "ExchangeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeAccount");
                });

            modelBuilder.Entity("CryptoStashStats.Models.ExchangeAccountBalance", b =>
                {
                    b.HasOne("CryptoStashStats.Models.ExchangeAccount", "ExchangeAccount")
                        .WithMany()
                        .HasForeignKey("ExchangeAccountId");

                    b.HasOne("CryptoStashStats.Models.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeAccount");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("CryptoStashStats.Models.ExchangeRate", b =>
                {
                    b.HasOne("CryptoStashStats.Models.Token", "BuyerToken")
                        .WithMany()
                        .HasForeignKey("BuyerTokenId");

                    b.HasOne("CryptoStashStats.Models.CurrencyExchange", "CurrencyExchange")
                        .WithMany()
                        .HasForeignKey("CurrencyExchangeId");

                    b.HasOne("CryptoStashStats.Models.Token", "SellerToken")
                        .WithMany()
                        .HasForeignKey("SellerTokenId");

                    b.Navigation("BuyerToken");

                    b.Navigation("CurrencyExchange");

                    b.Navigation("SellerToken");
                });

            modelBuilder.Entity("CryptoStashStats.Models.Wallet", b =>
                {
                    b.HasOne("CryptoStashStats.Models.Blockchain", "Blockchain")
                        .WithMany("Wallets")
                        .HasForeignKey("BlockchainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blockchain");
                });

            modelBuilder.Entity("CryptoStashStats.Models.WalletBalance", b =>
                {
                    b.HasOne("CryptoStashStats.Models.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoStashStats.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId");

                    b.Navigation("Token");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("ExchangeAccountToken", b =>
                {
                    b.HasOne("CryptoStashStats.Models.ExchangeAccount", null)
                        .WithMany()
                        .HasForeignKey("ExchangeAccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoStashStats.Models.Token", null)
                        .WithMany()
                        .HasForeignKey("TokensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TokenWallet", b =>
                {
                    b.HasOne("CryptoStashStats.Models.Token", null)
                        .WithMany()
                        .HasForeignKey("TokensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoStashStats.Models.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoStashStats.Models.Blockchain", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("CryptoStashStats.Models.ExchangeAccount", b =>
                {
                    b.Navigation("ExchangeAccountApiKey")
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoStashStats.Models.Token", b =>
                {
                    b.Navigation("NativeBlockchain");
                });
#pragma warning restore 612, 618
        }
    }
}
